"""TicketRepuesto actualizado (modelo)

Revision ID: 1c1a02510e7e
Revises: 2cb7ec2d7a62
Create Date: 2025-08-05 21:01:20.029164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c1a02510e7e'
down_revision = '2cb7ec2d7a62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_column('total')

    # ### end Alembic commands ###
