"""actualizado (modelo)

Revision ID: 4bcfbe54efe3
Revises: bbbcffdfa6a1
Create Date: 2025-08-05 17:14:24.105797

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4bcfbe54efe3'
down_revision = 'bbbcffdfa6a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.alter_column('estado_pago',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.String(length=4),
               existing_nullable=True)

    with op.batch_alter_table('ticket_repuesto', schema=None) as batch_op:
        batch_op.alter_column('estado_pago',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.String(length=4),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket_repuesto', schema=None) as batch_op:
        batch_op.alter_column('estado_pago',
               existing_type=sa.String(length=4),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)

    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.alter_column('estado_pago',
               existing_type=sa.String(length=4),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)

    # ### end Alembic commands ###
