"""upgrade grande (modelo)

Revision ID: 555b7184ce5b
Revises: 82b9ec8ebdb3
Create Date: 2025-08-12 00:01:20.467957

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '555b7184ce5b'
down_revision = '82b9ec8ebdb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_servicio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.String(length=500), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_de_pago', sa.DateTime(), nullable=True),
    sa.Column('estado_taller', sa.String(length=20), nullable=True),
    sa.Column('estado_pago', sa.String(length=20), nullable=True),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('vehiculo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['vehiculo_id'], ['vehiculo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ticket_servicio_detalle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket_servicio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('detalleticket')
    op.drop_table('ticket')
    with op.batch_alter_table('inventario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('precio_de_venta', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventario', schema=None) as batch_op:
        batch_op.drop_column('precio_de_venta')

    op.create_table('ticket',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('fecha_creacion', mysql.DATETIME(), nullable=True),
    sa.Column('vehiculo_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('motivo', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('observacion', mysql.TEXT(), nullable=True),
    sa.Column('fecha_de_pago', mysql.DATETIME(), nullable=True),
    sa.Column('estado_taller', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('estado_pago', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('total', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['vehiculo_id'], ['vehiculo.id'], name='ticket_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('detalleticket',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('descripcion', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('cantidad', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('precio_unitario', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('ticket_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('tipo', mysql.VARCHAR(length=20), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.id'], name=op.f('detalleticket_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('ticket_servicio_detalle')
    op.drop_table('ticket_servicio')
    # ### end Alembic commands ###
