"""Ticket actualizado (modelo)

Revision ID: 65f058b6a2bd
Revises: 7c7a0cc0aec8
Create Date: 2025-07-24 22:15:35.902600

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '65f058b6a2bd'
down_revision = '7c7a0cc0aec8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('observacion', sa.Text(), nullable=True))
        batch_op.drop_column('observaciones')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('observaciones', mysql.TEXT(), nullable=True))
        batch_op.drop_column('observacion')

    # ### end Alembic commands ###
