"""TicketRepuesto actualizado (modelo)

Revision ID: 6f59e685b285
Revises: 04dac1db541c
Create Date: 2025-07-24 20:47:30.891348

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6f59e685b285'
down_revision = '04dac1db541c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_repuesto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('tipo_repuesto', sa.String(length=50), nullable=False),
    sa.Column('tamano', sa.String(length=20), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio', sa.Integer(), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_de_termino', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('ticket_reparacion')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticket_reparacion',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('cliente_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('tipo_repuesto', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('tamano', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('cantidad', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('precio', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('total', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('observacion', mysql.TEXT(), nullable=True),
    sa.Column('fecha_creacion', mysql.DATETIME(), nullable=True),
    sa.Column('fecha_de_termino', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], name=op.f('ticket_reparacion_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('ticket_repuesto')
    # ### end Alembic commands ###
