""" actualizando modelos

Revision ID: 7703f508b559
Revises: d5f5e8ac8534
Create Date: 2025-08-05 16:36:02.561998

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7703f508b559'
down_revision = 'd5f5e8ac8534'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_de_pago', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('estado_taller', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('estado_pago', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('tipo', sa.String(length=20), nullable=False))
        batch_op.drop_column('fecha_de_termino')
        batch_op.drop_column('estado')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', mysql.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('fecha_de_termino', mysql.DATETIME(), nullable=True))
        batch_op.drop_column('tipo')
        batch_op.drop_column('estado_pago')
        batch_op.drop_column('estado_taller')
        batch_op.drop_column('fecha_de_pago')

    # ### end Alembic commands ###
