"""TicketRepuesto actualizado (modelo)

Revision ID: 7c7a0cc0aec8
Revises: 6f59e685b285
Create Date: 2025-07-24 21:25:50.003395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c7a0cc0aec8'
down_revision = '6f59e685b285'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket_repuesto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket_repuesto', schema=None) as batch_op:
        batch_op.drop_column('estado')

    # ### end Alembic commands ###
