"""inventario (modelo)

Revision ID: 82b9ec8ebdb3
Revises: 833f5e5e1169
Create Date: 2025-08-07 16:32:35.106449

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '82b9ec8ebdb3'
down_revision = '833f5e5e1169'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('porcentaje', sa.Float(), nullable=False))
        batch_op.drop_column('precio_venta')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('precio_venta', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_column('porcentaje')

    # ### end Alembic commands ###
