"""Actualizacion Inventario (modelo)

Revision ID: 833f5e5e1169
Revises: 1c1a02510e7e
Create Date: 2025-08-07 16:09:22.594734

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '833f5e5e1169'
down_revision = '1c1a02510e7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('precio_compra', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('precio_venta', sa.Integer(), nullable=False))
        batch_op.drop_column('precio')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('precio', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_column('precio_venta')
        batch_op.drop_column('precio_compra')

    # ### end Alembic commands ###
