"""TicketRepuesto actualizado (modelo)

Revision ID: bbbcffdfa6a1
Revises: c31e54f4b851
Create Date: 2025-08-05 16:48:32.008651

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bbbcffdfa6a1'
down_revision = 'c31e54f4b851'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('detalleticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo', sa.String(length=20), nullable=False))

    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_column('tipo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo', mysql.VARCHAR(length=20), nullable=False))

    with op.batch_alter_table('detalleticket', schema=None) as batch_op:
        batch_op.drop_column('tipo')

    # ### end Alembic commands ###
