""" actualizando modelos

Revision ID: c31e54f4b851
Revises: 7703f508b559
Create Date: 2025-08-05 16:37:35.774063

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c31e54f4b851'
down_revision = '7703f508b559'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket_repuesto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado_taller', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('fecha_de_pago', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('estado_pago', sa.Boolean(), nullable=True))
        batch_op.drop_column('fecha_de_termino')
        batch_op.drop_column('estado')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket_repuesto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', mysql.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('fecha_de_termino', mysql.DATETIME(), nullable=True))
        batch_op.drop_column('estado_pago')
        batch_op.drop_column('fecha_de_pago')
        batch_op.drop_column('estado_taller')

    # ### end Alembic commands ###
