"""Cliente actualizado (modelo)

Revision ID: d5f5e8ac8534
Revises: 65f058b6a2bd
Create Date: 2025-08-05 01:37:36.163044

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd5f5e8ac8534'
down_revision = '65f058b6a2bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.drop_column('estado')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', mysql.VARCHAR(length=20), nullable=False))

    # ### end Alembic commands ###
