"""actualizado (modelo)

Revision ID: df4b4f524aef
Revises: 555b7184ce5b
Create Date: 2025-08-12 00:54:48.550408

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'df4b4f524aef'
down_revision = '555b7184ce5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('precio_venta', sa.Integer(), nullable=False))
        batch_op.drop_column('precio_de_venta')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('precio_de_venta', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_column('precio_venta')

    # ### end Alembic commands ###
